version: '{branch}-{build}'
image: Ubuntu1804
environment:
  matrix:
  - TARGET: x86_64-unknown-linux-gnu
    CHANNEL: stable
  - TARGET: x86_64-unknown-linux-gnu
    CHANNEL: beta
  - TARGET: x86_64-unknown-linux-gnu
    CHANNEL: nightly
  - TARGET: i686-unknown-linux-gnu
    CHANNEL: stable
  - TARGET: i686-unknown-linux-gnu
    CHANNEL: beta
  - TARGET: i686-unknown-linux-gnu
    CHANNEL: nightly
install:
- sh: >-
    sudo apt-get update

    sudo apt-get install -y libnotmuch-dev gcc-multilib g++-multilib

    curl https://sh.rustup.rs -sSf -o rustup-init

    sh rustup-init --default-host $TARGET --default-toolchain $CHANNEL -y

    export PATH=$PATH:/home/appveyor/.cargo/bin

    rustc -Vv

    cargo -V
build: off
test_script:
- sh: cargo build --all-features --verbose --all
