[package]
name = "notcoal"
version = "0.2.0"
authors = ["eaon <eaon@mit.edu>"]
description = "Not charcoal filters, but notmuch ones."
repository = "https://ghom.niij.org/eaon/notcoal/"
license = "GPL-3.0"
readme = "README.md"
keywords = ["notmuch", "filter", "tagging"]
categories = ["command-line-utilities", "email"]

[dependencies]
notmuch = { git = "https://github.com/vhdirk/notmuch-rs.git" }
regex = "1"
serde = "1"
serde_json = "1"
serde_derive = "1"
structopt = { version = "0.2", optional = true }
dirs = { version = "1", optional = true }
rust-ini = { version = "0.13", optional = true }

[features]
standalone = ["structopt", "dirs", "rust-ini"]

[badges]
appveyor = { repository = "eaon/notcoal", service = "git" }
maintenance = { status = "actively-developed" }

[[bin]]
name = "notcoal"
required-features = ["standalone"]
