[package]
name = "notcoal"
version = "0.1.0"
authors = ["eaon <eaon@mit.edu>"]

[dependencies]
structopt = "0.2"
notmuch = "0.3"
rust-ini = "0.13"
dirs = "1"
subprocess = "0.1"
regex = "1"
serde = "1"
serde_json = "1"
serde_derive = "1"
