[package]
name = "notcoal"
version = "0.1.0"
authors = ["eaon <eaon@mit.edu>"]

[dependencies]
notmuch = { path = "../code-by-other-people/notmuch-rs" }
subprocess = "0.1"
regex = "1"
serde = "1"
serde_json = "1"
serde_derive = "1"
structopt = { version = "0.2", optional = true }
dirs = { version = "1", optional = true }
rust-ini = { version = "0.13", optional = true }

[features]
standalone = ["structopt", "dirs", "rust-ini"]

[[bin]]
name = "notcoal"
required-features = ["standalone"]
